# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f30f4c61e9daccbb774043ad51c3f339507057cd3c0d6c66940a035e9e882186d7e7efa236c9c20ef9ca2c84589d9e9ea10262c0f9b07fffa271ebab5a7b285a

test:
  secret_key_base: 06923e70c2a0c35186cb776ed00a4355ad8699bb089c61fe3043a9f94ed4773fa254caef6c07c8c82143206e1eda58c4d64f1aafd62a69b41b20ede64721280b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
